// Generated by Framer (224f28e)

import { addFonts, addPropertyControls, ControlType, cx, CycleVariantState, Image, useVariantState, withCSS } from "framer";
import { LayoutGroup, motion } from "framer-motion";
import * as React from "react";

const cycleOrder = ["aZr3VId7e"];

const variantClassNames = {aZr3VId7e: "framer-v-v9otqj"};

function addPropertyOverrides(overrides, ...variants) {
const nextOverrides = {}
variants?.forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]))
return nextOverrides
}

const humanReadableVariantMap = {};

const transitions = {default: {damping: 60, delay: 0, duration: 0.3, ease: [0.44, 0, 0.56, 1], mass: 1, stiffness: 500, type: "spring"}};

const toResponsiveImage = (value) => {
    if (typeof value === "object" && value !== null && typeof value.src === "string") {
        return value;
    };
    return typeof value === "string" ? {src: value} : undefined;
};


export interface Props extends React.HTMLAttributes<HTMLDivElement> { layoutId?: string | null; width?: number; height?: number; layoutDependency?: string | number; variant?: keyof typeof humanReadableVariantMap; image?: {src: string; srcSet?: string} }

const Component = React.forwardRef<HTMLDivElement, Props>(function({ id, style, className, width, height, layoutId, variant: outerVariant = "aZr3VId7e", image: Ci5UiqsB0 = {src: new URL("assets/qxBDoXazGcDs9pexNU1drrUdzh8.png", import.meta.url).href}, ...restProps }, ref) {

const outerVariantId = humanReadableVariantMap[outerVariant];

const variant = outerVariantId || outerVariant;

const {baseVariant, classNames, gestureVariant, setGestureState, setVariant, transition, variants} = useVariantState({cycleOrder, defaultVariant: "aZr3VId7e", transitions, variant, variantClassNames})
const layoutDependency = variants.join("-") + restProps.layoutDependency;

const defaultLayoutId = React.useId()

return (<LayoutGroup id={layoutId ?? defaultLayoutId}>
<motion.div initial={variant} animate={variants} onHoverStart={() => setGestureState({isHovered: true})} onHoverEnd={() => setGestureState({isHovered: false})} onTapStart={() => setGestureState({isPressed: true})} onTap={() => setGestureState({isPressed: false})} onTapCancel={() => setGestureState({isPressed: false})} className={cx("framer-ZTIwA", classNames)} style={{display: "contents"}}>
<motion.div {...restProps} className={cx("framer-v9otqj", className)} data-framer-name={"Variant 1"} layoutDependency={layoutDependency} layoutId={"aZr3VId7e"} ref={ref} style={{...style}} transition={transition}><Image background={{alt: "", fit: "fill", sizes: "18px", ...toResponsiveImage(Ci5UiqsB0)}} className={"framer-1izrwoe"} data-framer-name={"Captura de pantalla 2023-03-26 a las 16.40 1"} layoutDependency={layoutDependency} layoutId={"I1012:16769;960:16127"} transition={transition}/></motion.div>
</motion.div>
</LayoutGroup>)

});

const css = [".framer-ZTIwA [data-border=\"true\"]::after { content: \"\"; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }", "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-ZTIwA .framer-18v6c6j { display: block; }", ".framer-ZTIwA .framer-v9otqj { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 22px; justify-content: center; overflow: hidden; padding: 0px 0px 0px 0px; position: relative; width: 22px; }", ".framer-ZTIwA .framer-1izrwoe { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 18px); position: relative; width: 18px; }", "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-ZTIwA .framer-v9otqj { gap: 0px; } .framer-ZTIwA .framer-v9otqj > * { margin: 0px; margin-left: calc(0px / 2); margin-right: calc(0px / 2); } .framer-ZTIwA .framer-v9otqj > :first-child { margin-left: 0px; } .framer-ZTIwA .framer-v9otqj > :last-child { margin-right: 0px; } }"]

/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 22
 * @framerIntrinsicWidth 22
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"Ci5UiqsB0":"image"}
 */
const FramerltJuz9mWy: React.ComponentType<Props> = withCSS(Component, css, "framer-ZTIwA") as typeof Component;
export default FramerltJuz9mWy;

FramerltJuz9mWy.displayName = "asset/icon/status-pilot";

FramerltJuz9mWy.defaultProps = {height: 22, width: 22};

addPropertyControls(FramerltJuz9mWy, {Ci5UiqsB0: {__defaultAssetReference: "data:framer/asset-reference,qxBDoXazGcDs9pexNU1drrUdzh8.png?originalFilename=Captura+de+pantalla+2023-03-26+a+las+16.png&preferredSize=full", title: "Image", type: ControlType.ResponsiveImage}} as any)

addFonts(FramerltJuz9mWy, [])